### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by hosseinc** [zohvry/telegram_apps#1]
after giving it the password it returns

Traceback (most recent call last):
  File "C:\Users\@@@.py", line 65, in <module>
    getapi()
    ^^^^^^^^
  File "C:\Users\@@@.py", line 61, in getapi
    api_id = str(find_tag[0].find("span")).split('>')[2].split('<')[0]
                 ~~~~~~~~^^^
IndexError: list index out of range

**Comment by zohvry** [comment]
This code is writted to extract the api_id and api_hash and not to create them for the first time. This is why this error appears, but I will update it later. Thanks
